### ISSUE TITLE
Opening more Chests than you have

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#10]
Only had 1 Hero Chest, have it set to 2. Opened the 1st, said "Can't use chest" and the Opener buttons are greyed out like they do when they are running.
Closed CQAF, reopened it, went to chests, ran Normal chests with 3 (I had 2) and same result.
It's not releasing the action on the buttons with that error.

Speaking of "Error", was having the file "ErrorLog" intentional with no extension type? It's not a .txt like the other 2.

**Comment by Wiedmolol** [comment]
Fixed in last version.
