### ISSUE TITLE
No heroes selected?

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#17]
Don't know why, but I got the "No heroes selected. Do you want to run?" error msg. when DQ was trying to run.
My Settings.json has heroes selected. Actually has all of them selected. Also has my follower settings.
But the gen.cqinput file says I don't.

Settings.json:
  "defaultLowerLimit": "30%",
  "defaultUpperLimit": "100%",
  "calcEnabledHeroes": [
    "james",
    "hunter",
    "shaman",
    "alpha",
    "carl",
    "nimue",
    "athos",
    "jet",
    "geron",
    "rei",
    "ailen",
    "faefyr",
    "auri",
    "k41ry",
    "t4urus",
    "tr0n1x",
    "aquortis",
    "aeris",
    "geum",
    "rudean",
    "aural",
    "geror",
    "ourea",
    "erebus",
    "pontus",
    "oymos",
    "xarth",
    "atzar",
    "ladyoftwilight",
    "tiny",
    "nebra",
    "veildur",
    "brynhildr",
    "groth",
    "zeth",
    "koth",
    "gurth",
    "spyke",
    "aoyuki",
    "gaiabyte",
    "valor",
    "rokka",
    "pyromancer",
    "bewat",
    "nicte",
    "forestdruid",
    "ignitor",
    "undine",
    "chroma",
    "petry",
    "zaytus",
    "werewolf",
    "jackoknight",
    "dullahan",
    "ladyodelith",
    "shygu",
    "thert",
    "lordkirk",
    "neptunius",
    "sigrun",
    "koldis",
    "alvitr",
    "hama",
    "hallinskidi",
    "rigr",
    "aalpha",
    "aathos",
    "arei",
    "aauri",
    "atr0n1x",
    "ageum",
    "ageror",
    "christmaself",
    "reindeer",
    "santaclaus",
    "sexysanta",
    "toth",
    "ganah",
    "dagda",
    "bubbles",
    "apontus",
    "aatzar",
    "arshen",
    "rua",
    "dorth",
    "arigr",
    "hosokawa",
    "takeda",
    "hirate",
    "hattori",
    "adagda",
    "bylar",
    "boor",
    "bavah",
    "leprechaun",
    "sparks",
    "leaf",
    "flynn",
    "abavah",
    "hawking",
    "masterlee",
    "kumu-san",
    "liucheng",
    "hidoka"
  ],

gen.cqinput:
done
0
-1

y

Seems to be missing the enemy input as well. 1st time I'm seeing this happen.
Will monitor and see if it's just some weird glitch.

**Comment by Wiedmolol** [comment]
Why have you enabled heroes that you don't own? Like there is no way you have kumu-san, liucheng and hidoka.

Anyway, it kinda looks like the MacroCreator was unable to download your heroes and enemy lineup. All heroes with level 0 are ignored when gen.cqinput is created which would explain empty cqinput file but on the other hand the error you got doesn't care about hero levels - it pops up only if you have 0 heroes enabled, regardless of their level.

Problems with downloading data would also explain empty enemy string.

**Comment by Vitae666** [comment]
Selected "all heroes" and then "save to file" and I guess it saves even the ones I don't have...

**Comment by Wiedmolol** [comment]
Yeah, I've already made a change in the code so it won't select not-owned heroes but I'm gonna wait before I upload it cause I need to check if settings are handled correctly.

**Comment by Vitae666** [comment]
Thanks. Seems to be working good now :)
