### ISSUE TITLE
Dung Question

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#23]
Just want to make sure that clicking "Solve Dungeons now" when available in CQAF, that it opening CQMC and then having to manually click "Get Dung" and then Run is the correct expected results.
Somehow I thought that clicking Solve would just run it like it does the DQ's. In the background.

**Comment by saynotoid** [comment]
i can only confirm that it is the way im using the app each time the dung is available as well:) would be nice to have it working the same way the main DQ is:) app v0.9.9
