### ISSUE TITLE
Auto-Level Question

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#24]
"It will automatically level chosen heroes with prana/CC/AS. You can also convert AS to prana."
Ok, I have 10 Prana and 90 AS (at this time). I have Geum set to lvl with Prana. Shouldn't CQAF convert at least 20 of my AS to Prana so that it will use 12 Prana to level him up? It's been almost a day and nothing's happened. I had less AS before, but it was more than 50 so it wasn't a lack of AS.
I don't see an option to DO the change of AS to Prana, I'm just assuming that it will do the conversion itself.
Am I missing something?

**Comment by Wiedmolol** [comment]
You can choose "Convert to Prana" in AS Hero list.

**Comment by Vitae666** [comment]
Ahh..thought it was a checkbox I was missing. In case i wanted to level a hero with AS as well.
So it's either lvl with AS or convert.
