### ISSUE TITLE
Ascended Geum not leveling

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#32]
Got it a few days ago and it hasn't levelled since I got it.
I deleted all my logs just before the 4hr timer for it on CQAF counted down to 0 and my ErrorLog got those "Server error" errors in it repeatedly.
No idea if it's all related to it, but since I didn't have an ErrorLog one second and the next, I did when the timer ran down....
I used CQAF to level up Geum with no problem. 
I don't know, but I doubt that whole need to be connected to the server thing in my other post is related to this. I didn't get it this time and the other times they were less than 4hrs apart and happened so often, 15 to 13 mins apart that I don't think it had anything to do with the Bosses or DQ's.
Also, I don't have the "Wait for autoLevel after WB changes" checked.

8/17/2018 10:15:00 PM
8/17/2018 10:15:00 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 10:15:04 PM
8/17/2018 10:15:04 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 10:15:08 PM
8/17/2018 10:15:12 PM
8/17/2018 10:15:12 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 10:15:16 PM
8/17/2018 10:15:16 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}
8/17/2018 10:15:20 PM
	Error Cloud Script Error: level super {"ok":false,"err":"Server error"}

![capture](https://user-images.githubusercontent.com/9310914/44294914-fa0b1c80-a26c-11e8-9c67-a0c104f59716.JPG)
![image](https://user-images.githubusercontent.com/9310914/44294922-0f804680-a26d-11e8-9b82-4fe9eadbf4a1.png)

**Comment by robgw84** [comment]
The ascended ones dont see to work with the auto level, the scaling cost seems to be an issue. I have noticed the same thing with Master Lee.

**Comment by Vitae666** [comment]
Ok. Thought it was more of an
#if button = exist then click
Guess it's looking for a set cost text?

**Comment by robgw84** [comment]
I kind of think that they just copied the code for the other level ups but it didnt work. I dont know for sure though. I havent checked the code for it.

Hmm I dont understand the code enough to know whats going on, if i knew what each of the variables meant then I could figure it out. Sadly no commenting in it.
