### ISSUE TITLE
CQMacroCreator crashes when running AutoDQ

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#4]
I have it set up, checked off, told it to run, and then it crashed. I am unsure if it's because I'm as far into the DQ as I can currently get, DQ66
Would have to wait until it resets to verify.
I am using the latest CQMacroCreator (BTW, CQMC should have a version # somewhere on it. Just sayin' :) )
![capture](https://user-images.githubusercontent.com/9310914/39222527-2376ac54-480b-11e8-978f-53eb5443f1e6.JPG)

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	CQMacroCreator.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5adf0419
  Problem Signature 04:	System.Windows.Forms
  Problem Signature 05:	4.7.2558.0
  Problem Signature 06:	59d4145b
  Problem Signature 07:	cc4
  Problem Signature 08:	23
  Problem Signature 09:	System.ObjectDisposedException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0b75
  Additional Information 2:	0b75568a0e6063f8cf7482f4e14934ab
  Additional Information 3:	c0ea
  Additional Information 4:	c0ea3fb5f3ebb5e9eecf94b5491c3827

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt

**Comment by Wiedmolol** [comment]
It looks like it's a problem with CQMC honestly. I will look into it.

**Comment by Vitae666** [comment]
Kewl. Thanks 😊

**Comment by Vitae666** [comment]
Wanted to post this yesterday, but figured another day of testing would be better confirmation.
CQMC crashes when I reach the max possible DQ. So, it's not that it's "just crashing" it's for a reason. 
Not that any crash is good, but it could be for a worse reason.
Why it crashes when in conjunction with CQAF is the question.

**Comment by Wiedmolol** [comment]
Just a question - have you updated CQMC lately? The new version was released together with new CQAutomater.

**Comment by Vitae666** [comment]
Yup. Downloaded both at the same time. I'd give you a version #, but there is none on there like there is for CQAF *hint hint* ;-)

BTW, maybe I'm crazy, ok, I AM crazy, but that's not the point!
But I don't see CosmosQuest.exe running as a process when using CQAF for the DQ. 
I only see it running when I use CQMC.

**Comment by Wiedmolol** [comment]
Honestly I don't know why it crashes. When I use it I don't get any errors or exceptions whatsoever. That said I've uploaded new version of both automater and CQMC so let me know if it still crashes after update.

**Comment by Vitae666** [comment]
Funny thing, today it didn't crash. Haven't downloaded new versions. Came back from work, and it was fine. No idea why the past 2 days it had.
Going to get the new versions now.
