### ISSUE TITLE
Broken Remembering Settings & a Suggestion

### ISSUE THREAD

**Issue by Vitae666** [Wiedmolol/CQAutomater#6]
Remembering "Sound Notification" setting seems broken.
"DQSoundEnabled": false,
But when it's started, it's always Enabled.
When it's enabled and I click Save it still says
"DQSoundEnabled": false,

Chest Opener doesn't seem to have a saved setting.
I always set it to 2, but when I restart, it's always 0. And I don't see a corresponding setting in the json.

Suggestion:
How about an "Open All Chests" button? Reads the # of chests you have, maybe via a refresh, and opens each of them. But have it a bit separated from the "Chest Opener" box so that it's less likely that people will click THAT by mistake.

**Comment by Wiedmolol** [comment]
Fixed setting for DQ Sound, added setting for chest opener. For now I won't add "Open all chests" button. I don't think it's really needed.

**Comment by Vitae666** [comment]
Thanks.
Yeah, no worries on the Open all chests. Was just a thought from a lazy ass that didn't want to press 2 buttons LOL ;-)
